In [19]:
import pandas as pd
import matplotlib.pyplot as pl
import torch
# import transformers as ppb
import keras

Using TensorFlow backend.

In [2]:
df=pd.read_csv('water_problem_nlp_en_for_Kaggle_100.csv',
               encoding='latin-1',
              delimiter=';')

In [3]:
df.fillna(0,inplace=True)
df.head(10)

,text,env_problems,pollution,treatment,climate,biomonitoring
0,In the Southern Bug basin wastewater is discha...,1,1.0,0.0,0.0,0.0
1,This amount is distributed as follows: urban a...,1,1.0,0.0,0.0,0.0
2,Despite the similar volumes of discharged wast...,1,1.0,0.0,0.0,0.0
3,They bring 84% of organic pollution 86% of pho...,1,1.0,0.0,0.0,0.0
4,The input of the industry is between 7â21% a...,1,1.0,0.0,0.0,0.0
5,Settlements that do not have sewage systems us...,1,0.0,1.0,0.0,0.0
6,Equipment of WWTPs is very worn-out the amount...,1,0.0,1.0,0.0,0.0
7,The current state of sewage networks is a sour...,1,0.0,1.0,0.0,0.0
8,Consequently in Ukraine on average 2 accidents...,1,1.0,0.0,0.0,0.0
9,The load of pollutants from accidental dischar...,0,0.0,0.0,0.0,0.0

In [4]:
df=df.astype({
    'text':str,
    'pollution':int,
    'treatment':int,
    'climate':int,
    'biomonitoring':int
})
df.head()

,text,env_problems,pollution,treatment,climate,biomonitoring
0,In the Southern Bug basin wastewater is discha...,1,1,0,0,0
1,This amount is distributed as follows: urban a...,1,1,0,0,0
2,Despite the similar volumes of discharged wast...,1,1,0,0,0
3,They bring 84% of organic pollution 86% of pho...,1,1,0,0,0
4,The input of the industry is between 7â21% a...,1,1,0,0,0

In [5]:
df.shape

(100, 6)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   text           100 non-null    object
 1   env_problems   100 non-null    int64
 2   pollution      100 non-null    int32
 3   treatment      100 non-null    int32
 4   climate        100 non-null    int32
 5   biomonitoring  100 non-null    int32
dtypes: int32(4), int64(1), object(1)
memory usage: 3.2+ KB

In [18]:
df.iloc[:,1:]

    env_problems  pollution  treatment  climate  biomonitoring
0              1          1          0        0              0
1              1          1          0        0              0
2              1          1          0        0              0
3              1          1          0        0              0
4              1          1          0        0              0
..           ...        ...        ...      ...            ...
95             0          0          0        0              0
96             0          0          0        0              0
97             0          0          0        0              0
98             0          0          0        0              0
99             0          0          0        0              0

[100 rows x 5 columns]